import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '../components/Footer'
import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

const Header = dynamic(() => import('../components/Header'), {
   ssr: false,
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang='en'>
         <body className={inter.className}>
            <Header />
            <main className='bg-[#F1F1F1]'>{children}</main>
            <Footer />
         </body>
      </html>
   )
}
